### ISSUE TITLE
Some suggestions regarding this project

### ISSUE THREAD

**Issue by anonrig** [altayer-digital/ATGMediaBrowser#6]
Hello!

First of all, thank you for developing such a smooth pod. Unfortunately, I've come up with a several issues while trying to use this pod in my current project. I've some several suggestions to improve this project and if needed I can help develop it.

- MediaBrowserViewController can't be used as a subclass because of the use of `public` class. A quick fix is to use `open`.
- MediaBrowserViewController doesn't handle item count as 0. This is a problem working with async requests, since in the initial view load, the contents are 0, and then it's filled through either network request or file system req.
- MediaBrowserViewController should have an empty state view, to indicate there's nothing to view. (This is related to the 2nd issue)
- MediaBrowserViewConroller delegate can be and should be initialized after the constructor. Since, the developer may want to listen for delegate method changes after the view appeared, loaded etc.
- There can be a support for RxSwift that can remove the uses of delegates and just use reactive programming to handle content change/reload.
- Close button on top removes the ability for developers to use this pod as a tab inside tabbar controller. A simple check if the page is a root view controller can fix this.

Hope this clears somethings from a `user` perspective of the pod.

Btw, say hello to @mehmettamturk from me!

**Comment by surajthomask** [comment]
Hey @anonrig,  

Thanks for the great feedback and suggestions. About the suggestions you added, please feel free to create pull requests with necessary changes. I have added comments on some of the suggestions below.

As for the suggestion regarding the item count as 0, media browser does takes care of it. But as you mentioned in next point, it just shows a blank view. It would be really nice to add an empty view that is configurable like how the close button can be configured now.

As for the delegate, it's an optional variable. You can avoid passing the delegate object while initialization and set it later. If you meant the data source, it's a required parameter as of now. 

Associating a reusable component with any programming-paradigm/ framework is something we try to actively avoid. Even though RxSwift is an amazing framework, there are tons of people who do not use the same. So associating the framework with RxSwift inside the framework itself is something we will not encourage.

To remove the close button, you can simply set the passed in variable's `isHidden` property to `true` in the delegate call back `func mediaBrowser(_ mediaBrowser: MediaBrowserViewController, updateCloseButton button: UIButton)`.

Once again thanks for the feedback and suggestions. And @mehmettamturk  says `Hi`
